### ISSUE TITLE
Reference hover needs a contrasting color

### ISSUE THREAD

**Issue by pburneux** [CanKolay3499/base46#1]
Hello,

Awesome work. I know this repo is new, but I'm already using it. 

I wanted to point out that the cmp window should probably have a contrasting color:

![image](https://user-images.githubusercontent.com/5706123/203874335-db882c62-8d65-4dce-b862-76c6c48b8315.png)

**Comment by CanKolay3499** [comment]
I know that issue but don't have time to fix it. I'll try to fix that as soon as possible.

**Comment by pburneux** [comment]
What I've done for now is to not call base46.setup() and instead i am just calling the plugins that I want to use, like:
`require('base46').load_highlight('telescope')`

**Comment by CanKolay3499** [comment]
I've found that issue is not caused by this plugin. Just add CursorLine:PmenuSel to your cmp winhighlight config https://github.com/CanKolay3499/CNvim/blob/e03d7ee4eca183f156a22a3e0d1334e6ea08d612/lua/plugins/config/cmp.lua#L28
